export const COLORS =
    [
        "purple",
        "green",
        "red",
        "yellow",
        "orange",
        "lightCoral",
        "palegoldenrod",
        "violet",
        "springgreen",
        "slategray",
        "aquamarine",
        "cadetblue",
        "chocolate",
        "fuchsia",
        "limegreen",
        "darkturquoise"
    ]
